#!/bin/bash
pip install flask flask_cors bs4 lxml pelican markdown gevent

# Update Git submodules
git submodule update --init

# Install Python packages using pip

# Optionally, you can add more commands or customizations here.
